tags:
    - name: Labels

schemes:
  - http
paths:
delete:
  tags:
    - Labels
  summary: Find label by pk
  description: delete  single label
  operastionId: getLabelById
  parameters:
    - name: pk
      in: path
      required: true
      type: integer
    - name: token
      in: header
      description: token
  responses:
    200:
      description: OK
put:
  tags:
    - Labels
  summary: Find label by pk
  description: Returns a single label and update label
  parameters:
    - name: pk
      in: path
      required: true
      type: integer
    - name: token
      in: header
      description: token
    - name: body
      in: body
      required: true
      schema:
        $ref: "#/definitions/Labels"
  responses:
    200:
      description: OK
post:
  tags:
    - Labels
  parameters:
    - name: body
      in: body
      required: true
      schema:
        $ref: "#/definitions/Labels"
    - name: token
      in: header
      description: token
  responses:
    200:
      description: OK
get:
    tags:
      - Labels
    summary: Find label by pk
    description: Returns a single label
    parameters:
      - name: pk
        in: path
        required: true
        type: integer
      - name: token
        in: header
        description: token
responses:
  200:
    description: |
      Result

definitions:
  Labels:
    properties:
      label:
        type: string