tags:
    - name: Notes

schemes:
  - http
paths:
delete:
  tags:
    - Notes
  summary: Find note by pk
  description: Returns a single note
  operastionId: getNoteById
  parameters:
    - name: pk
      in: path
      required: true
      type: integer
    - name: token
      in: header
      description: token
  responses:
    200:
      description: OK
put:
  tags:
    - Notes
  summary: Find note by pk
  description: Returns a single note
  parameters:
    - name: pk
      in: path
      required: true
      type: integer
    - name: token
      in: header
      description: token
    - name: body
      in: body
      required: true
      schema:
        $ref: "#/definitions/Notes"
  responses:
    200:
      description: OK
post:
  tags:
    - Notes
  parameters:
    - name: body
      in: body
      required: true
      schema:
        $ref: "#/definitions/Notes"
    - name: token
      in: header
      description: token
  responses:
    200:
      description: OK
get:
    tags:
      - Notes
    summary: Find note by pk
    description: Returns a single note
    parameters:
      - name: pk
        in: path
        type: integer
      - name: token
        in: header
        description: token
responses:
  200:
    description: |
      Result
#/register/user:
#  post:
#    tags:
#      - users
#    summary: create user
#    description: create user api
#    parameters:
#      - name: body
#        in: body
#        required: true
#        schema:
#          $ref: "#/definitions/Users"
#    responses:
#      200:
#        description: |
#          Result


definitions:
  Notes:
    properties:
      title:
        type: string
      description:
        type: string
      color:
        type: string
      is_deleted:
        type: boolean
      is_archived:
        type: boolean
      is_pinned:
        type: boolean
      is_restored:
        type: boolean
      is_trashed:
        type: boolean
      label:
        type: integer

#  Users:
#    properties:
#      firstName:
#        type: string
#      lastName:
#        type: string
#      email:
#        type: string
#      password:
#        type: string
#      phone_numbar:
#        type: string
#      is_active:
#        type: boolean

#  Labels:
#    properties:
#      label:
#        type: string
