class Config:
    FUNDOO_USERS_MYSQL_DB_USERNAME = 'root'
    FUNDOO_USERS_MYSQL_DB_PASSWORD = 'root'
    FUNDOO_USERS_MYSQL_DB_NAME = 'microservice_db'
    FUNDOO_USERS_MYSQL_DB_HOST = '127.0.0.1'
    FUNDOO_USERS_MYSQL_DB_PORT = 3306
    FUNDOO_USER_PASSWORD_SECURITY_SALT = '$2b$12$p4Es1DYfI6obeKvBqFNR3O'
    FUNDOO_USERS_JWT_SECRET_KEY = 'micro_jwt'
    FUNDOO_USERS_REDIS_CACHE_HOST = '127.0.0.1'
    FUNDOO_USERS_REDIS_CACHE_PORT = 6379
    FUNDOO_USERS_REDIS_CACHE_PASSWORD = ''
    FUNDOO_USERS_EMAIL_PORT = 587
    FUNDOO_USERS_EMAIL_HOST = 'smtp.gmail.com'
    FUNDOO_USERS_EMAIL_HOST_USERNAME = 'bhaktibj402@gmail.com'
    FUNDOO_USERS_EMAIL_HOST_PASSWORD = 'Bhaktijadhav'
    FUNDOO_USERS_HOST_LINK = 'http://127.0.0.1:9002'
